In [12]:
import pandas as pd
import numpy as np
import ast

In [94]:
df_reviews = pd.read_csv('./data/reviews.csv', encoding = 'utf-8')
df_reviews.head()

C:\Users\raxmo\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"03 11, 2013",A3478QRKQDOPQ2,0001527665,{'Format:': ' VHS Tape'},jacki,really happy they got evangelised .. spoiler a...,great,1362960000,NaN,NaN
1,5,True,"02 18, 2013",A2VHSG6TZHU1OB,0001527665,{'Format:': ' Amazon Video'},Ken P,Having lived in West New Guinea (Papua) during...,Realistic and Accurate,1361145600,3,NaN
2,5,False,"01 17, 2013",A23EJWOW1TLENE,0001527665,{'Format:': ' Amazon Video'},Reina Berumen,Excellent look into contextualizing the Gospel...,Peace Child,1358380800,NaN,NaN
3,5,True,"01 10, 2013",A1KM9FNEJ8Q171,0001527665,{'Format:': ' Amazon Video'},N Coyle,"More than anything, I've been challenged to fi...",Culturally relevant ways to share the love of ...,1357776000,NaN,NaN
4,4,True,"12 26, 2012",A38LY2SSHVHRYB,0001527665,{'Format:': ' Amazon Video'},Jodie Vesely,This is a great movie for a missionary going i...,Good Movie! Great for cross-cultural missionar...,1356480000,NaN,NaN

In [95]:
df = df_reviews.copy()

In [96]:
# Filter for only string values that contain the dictionary string
mask = df['style'].apply(lambda x: isinstance(x, str) and "{'Format:" in x)
df = df.loc[mask]

# Convert the string dictionary to a dictionary data type
df['style'] = df['style'].apply(lambda x: ast.literal_eval(x))

# Extract the value for the dictionary key 'Format:' for each row
df['style'] = df['style'].apply(lambda x: x['Format:'])

# Assign this extracted value back to the 'style' column in the dataframe
df['style'] = df['style'].astype(str)

df.head()

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"03 11, 2013",A3478QRKQDOPQ2,0001527665,VHS Tape,jacki,really happy they got evangelised .. spoiler a...,great,1362960000,NaN,NaN
1,5,True,"02 18, 2013",A2VHSG6TZHU1OB,0001527665,Amazon Video,Ken P,Having lived in West New Guinea (Papua) during...,Realistic and Accurate,1361145600,3,NaN
2,5,False,"01 17, 2013",A23EJWOW1TLENE,0001527665,Amazon Video,Reina Berumen,Excellent look into contextualizing the Gospel...,Peace Child,1358380800,NaN,NaN
3,5,True,"01 10, 2013",A1KM9FNEJ8Q171,0001527665,Amazon Video,N Coyle,"More than anything, I've been challenged to fi...",Culturally relevant ways to share the love of ...,1357776000,NaN,NaN
4,4,True,"12 26, 2012",A38LY2SSHVHRYB,0001527665,Amazon Video,Jodie Vesely,This is a great movie for a missionary going i...,Good Movie! Great for cross-cultural missionar...,1356480000,NaN,NaN

In [56]:
dfnew = df[df['style'].str.contains('Amazon Video|Prime Video')]
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3722283 entries, 1 to 8765542
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   overall         int64
 1   verified        bool
 2   reviewTime      object
 3   reviewerID      object
 4   asin            object
 5   style           object
 6   reviewerName    object
 7   reviewText      object
 8   summary         object
 9   unixReviewTime  int64
 10  vote            object
 11  image           object
dtypes: bool(1), int64(2), object(9)
memory usage: 344.3+ MB

In [60]:
df_features = dfnew[dfnew['verified'] == True]
df_features['asin'].value_counts()

B01BHTSIOC    20540
B00006CXSS    17211
B00YSG2ZPA    17105
B00NAQ3EOK    16415
B00WNBABVC    14014
              ...
B000BM7YWY        1
B001675YTI        1
B00005UERJ        1
B0027AB98I        1
B000E3LCYG        1
Name: asin, Length: 28156, dtype: int64

In [69]:
df_features = df_features.drop(['image', 'verified', 'unixReviewTime'], axis=1)

In [70]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3077240 entries, 1 to 8765523
Data columns (total 9 columns):
 #   Column        Dtype
---  ------        -----
 0   overall       int64
 1   reviewTime    object
 2   reviewerID    object
 3   asin          object
 4   style         object
 5   reviewerName  object
 6   reviewText    object
 7   summary       object
 8   vote          object
dtypes: int64(1), object(8)
memory usage: 234.8+ MB

### Note: Creating new .csv file so that it is more manageable to work from

In [71]:
df_features.to_csv('./data/reviews_streaming.csv', encoding='utf-8', index=False)

In [20]:
df_meta = pd.read_csv('./data/reviews_meta.csv', encoding = 'utf-8')
df_meta.head()

C:\Users\raxmo\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (1,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,category,tech1,description,fit,title,also_buy,tech2,brand,feature,rank,also_view,main_cat,similar_item,date,price,asin,imageURL,imageURLHighRes,details
0,"['Movies & TV', 'Movies']",NaN,[],NaN,Understanding Seizures and Epilepsy,[],NaN,NaN,[],"886,503 in Movies & TV (",[],Movies & TV,NaN,NaN,NaN,0000695009,[],[],NaN
1,"['Movies & TV', 'Movies']",NaN,[],NaN,Spirit Led&mdash;Moving By Grace In The Holy S...,[],NaN,NaN,[],"342,688 in Movies & TV (",[],Movies & TV,NaN,NaN,NaN,0000791156,['https://images-na.ssl-images-amazon.com/imag...,['https://images-na.ssl-images-amazon.com/imag...,NaN
2,"['Movies & TV', 'Movies']",NaN,['Disc 1: Flour Power (Scones; Shortcakes; Sou...,NaN,My Fair Pastry (Good Eats Vol. 9),[],NaN,Alton Brown,[],"370,026 in Movies & TV (",[],Movies & TV,NaN,NaN,NaN,0000143529,['https://images-na.ssl-images-amazon.com/imag...,['https://images-na.ssl-images-amazon.com/imag...,NaN
3,"['Movies & TV', 'Movies']",NaN,['Barefoot Contessa Volume 2: On these three d...,NaN,"Barefoot Contessa (with Ina Garten), Entertain...","['B002I5GNW4', 'B005WXPVMM', 'B009UY3W8O', 'B0...",NaN,Ina Garten,[],"342,914 in Movies & TV (","['B002I5GNW4', '0804187045', 'B009UY3W8O', '06...",Movies & TV,NaN,NaN,$74.95,0000143588,[],[],NaN
4,"['Movies & TV', 'Movies']",NaN,['Rise and Swine (Good Eats Vol. 7) includes b...,NaN,Rise and Swine (Good Eats Vol. 7),"['B000P1CKES', 'B000NR4CRM']",NaN,Alton Brown,[],"351,684 in Movies & TV (",['B0015SVNXY'],Movies & TV,NaN,NaN,NaN,0000143502,['https://images-na.ssl-images-amazon.com/imag...,['https://images-na.ssl-images-amazon.com/imag...,NaN

In [21]:
df2 = df_meta.copy()

In [130]:
df2['details'].value_counts().head(10)

{}                                                                                                                  101
{'Language:': 'English', 'Subtitles:': 'English', 'ASIN: ': 'B0000WN1MW'}                                             3
{'Language:': 'English', 'ASIN: ': 'B0002OI038'}                                                                      2
{'ASIN: ': 'B00000JLXE'}                                                                                              2
{'ASIN: ': 'B00009KTW4'}                                                                                              2
{'Language:': 'English', 'ASIN: ': 'B0001WTV98'}                                                                      2
{'Language:': 'English', 'Subtitles:': 'English, French, Spanish', 'Dubbed:': 'English', 'ASIN: ': 'B00005JNA7'}      2
{'Dubbed:': 'English', 'ASIN: ': 'B00005M2BX'}                                                                        2
{'Language:': 'Hungarian', 'Subtitles:': 'English', 'ASIN: ': 'B00008RH3E'}                                           2
{'Subtitles:': 'English', 'ASIN: ': 'B00004RFGK'}                                                                     2
Name: details, dtype: int64

to drop: 
1. tech1 (not applicable for my project)
2. fit (not applicable for my project)
3. tech2 (not applicable for my project)
4. similar_item (no entries)
5. feature (just describes the content similar to 
5. imageURL (not useful for my project)
6. ImageURLHighRes

not sure if will be useful:

# Data Understanding: colum/feature definitions


### reviews.csv:
1. **overall** = product rating from 1-5 stars
2. **verivied** = the review comes from a user who was verified to have bought the product
3. **reviewTime** = date that the review was made
4. **reviewrID** = Amazon User Id for the reveiw
5. **asin** = Amazon Standard Identification Number
6. **style** = format of the video/movie (only going to look at prime video and amazon video as they are both streams)
6. **reviewerName** = name of reviewer (will want to get rid of this column)
7. **reviewText** = the text of the actual review
8. **summary** = headline/summary the reviewer uses to summarize their review
9. **unixReviewTime** = time of the review (formated in unix time)
10. **vote** = amount of votes a review recieved. Other users can mark a review as helpful. Think of it as a like button.
11. **image** = url of profile image for reviewer


### reviews_meta.csv:

1. **category** = List of main category of product and sub category, in this instance 'Genre' is located in the subcategory.
23. **tech1** = N/A
3. **description** = amazon description of product/synopsis of movie/tv
4. **fit** = used for products that have fits (clothes)
5. **title** = Title of the product/movie/tv show
6. **also_buy** = recomendation from amazon to buy product if you're viewing this product
7. **tech2** = N/A
8. **brand** = seems like the owner of the media or the distributor. But will not be important in identifying movies.
9. **feature** = similar to style but more granular. will not be using this column
10. **rank** = 
11. **also_view** =
12. **main_cat** =
13. **similar_item** =
14. **date** =
15. **price** =
16. **asin** =
17. **imageURL** =
18. **imageURLHighRes** =
19. **details** =


## note: going to filter so that all 'asin' have a movie title

Collab data:
1. **overall** = product rating from 1-5 stars
2. **reviewTime** = date that the review was made
3. **reviewrID** = Amazon User Id for the reveiw
4. **style** = format of the video/movie (only going to look at 'prime video' and 'amazon video' as they are both streams)
5. **title** = Title of the product/movie/tv show

Collab data unsure if will use:
1. **summary** = headline/summary text the reviewer uses to summarize their review
2. **reviewText** = the text of the actual review
3. **vote** = amount of votes a review recieved. Other users can mark a review as helpful. Think of it as a like button.

Content based data:
1. **title** = Title of the product/movie/tv show
2. **category** = List of lists main category of product and sub category, in this instance the 'Genre' of a movie in this column.
3. **description** = amazon description of product/synopsis of movie/tv
4. **rank** = ranked by amount of purchases and positive reviews for each.

Content data unsure if will use:
1. **also_buy** = recomendation from amazon to buy product if you're viewing this product (may be used to benchmark my recomendation classification)
2. **also_view** = similar to 'also_buy' 
3. **details** = information about language, dubbed, and subtitles here and may be important but not sure

# looked at the smaller subset of reviews and  I'm going to go with the larger set of reviews but hanging on to the data for now in case I find something strange with the larger set.

In [85]:
df_core = pd.read_csv('./data/subset_reviews.csv', encoding='utf-8')
df_core.head()

C:\Users\raxmo\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"11 9, 2012",A2M1CU2IRZG0K9,0005089549,{'Format:': ' VHS Tape'},Terri,So sorry I didn't purchase this years ago when...,Amazing!,1352419200,NaN,NaN
1,5,True,"12 30, 2011",AFTUJYISOFHY6,0005089549,{'Format:': ' VHS Tape'},Melissa D. Abercrombie,Believe me when I tell you that you will recei...,Great Gospel VHS of the Cathedrals!,1325203200,NaN,NaN
2,5,True,"04 21, 2005",A3JVF9Y53BEOGC,000503860X,{'Format:': ' DVD'},Anthony Thompson,"I have seen X live many times, both in the ear...",A great document of a great band,1114041600,11,NaN
3,5,True,"04 6, 2005",A12VPEOEZS1KTC,000503860X,{'Format:': ' DVD'},JadeRain,"I was so excited for this! Finally, a live co...",YES!! X LIVE!!,1112745600,5,NaN
4,5,True,"12 3, 2010",ATLZNVLYKP9AZ,000503860X,{'Format:': ' DVD'},T. Fisher,X is one of the best punk bands ever. I don't ...,X have still got it,1291334400,5,NaN

In [97]:
mask2 = df_core['style'].apply(lambda x: isinstance(x, str) and "{'Format:" in x)
df_core = df_core.loc[mask2]

# Convert the string dictionary to a dictionary data type
df_core['style'] = df_core['style'].apply(lambda x: ast.literal_eval(x))

# Extract the value for the dictionary key 'Format:' for each row
df_core['style'] = df_core['style'].apply(lambda x: x['Format:'])

# Assign this extracted value back to the 'style' column in the dataframe
df_core['style'] = df_core['style'].astype(str)

df_core.head()

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"11 9, 2012",A2M1CU2IRZG0K9,0005089549,VHS Tape,Terri,So sorry I didn't purchase this years ago when...,Amazing!,1352419200,NaN,NaN
1,5,True,"12 30, 2011",AFTUJYISOFHY6,0005089549,VHS Tape,Melissa D. Abercrombie,Believe me when I tell you that you will recei...,Great Gospel VHS of the Cathedrals!,1325203200,NaN,NaN
2,5,True,"04 21, 2005",A3JVF9Y53BEOGC,000503860X,DVD,Anthony Thompson,"I have seen X live many times, both in the ear...",A great document of a great band,1114041600,11,NaN
3,5,True,"04 6, 2005",A12VPEOEZS1KTC,000503860X,DVD,JadeRain,"I was so excited for this! Finally, a live co...",YES!! X LIVE!!,1112745600,5,NaN
4,5,True,"12 3, 2010",ATLZNVLYKP9AZ,000503860X,DVD,T. Fisher,X is one of the best punk bands ever. I don't ...,X have still got it,1291334400,5,NaN

In [98]:
df_core['style'].value_counts()

 DVD                                1518818
 Amazon Video                        950519
 Blu-ray                             308711
 Prime Video                         147662
 VHS Tape                             58533
 HD DVD                                1396
 DVD-R                                 1288
 Theatrical Release                     689
 Audio CD                               613
 DVD-ROM                                470
 UMD for PSP                            330
 Amazon Instant Video                   223
 Electronics                            107
 Hardcover                              101
 Interactive DVD                         93
 Paperback                               84
 Laser Disc                              76
 DVD Audio                               49
 Kindle Edition                          32
 MP3 Music                               32
 Unknown Binding                         31
 Toy                                     30
 CD-ROM                                  25
 Staple Bound                            19
 Misc.                                   18
 Video CD                                13
 Wireless Phone Accessory                12
 Kindle Edition with Audio/Video         11
 Grocery                                  9
 Kitchen                                  8
 Audio Cassette                           8
 Office Product                           7
 Mass Market Paperback                    5
 Videotape                                5
 Vinyl                                    4
 Audible Audiobook                        3
 Misc. Supplies                           2
 MiniDisc                                 2
 Video Game                               2
 Accessory                                1
 Unbound                                  1
 MP3 CD                                   1
 Product Bundle                           1
 S-VHS                                    1
Name: style, dtype: int64